import { NextRequest, NextResponse } from 'next/server'
import Anthropic from '@anthropic-ai/sdk'
import { google } from 'googleapis'
import { getAuthedClient } from '@/lib/google'
import path from 'path'
import fs from 'fs/promises'

function isAuthorized(req: NextRequest) {
  return req.headers.get('authorization') === `Bearer ${process.env.CRON_SECRET}`
}

const TZ = 'Europe/Budapest'

async function findGhlContact(query: string): Promise<{ id: string; name: string } | null> {
  if (!process.env.GHL_API_KEY || !query) return null
  try {
    const res = await fetch(
      `https://services.leadconnectorhq.com/contacts/?locationId=${process.env.GHL_LOCATION_ID}&query=${encodeURIComponent(query)}&limit=1`,
      { headers: { Authorization: `Bearer ${process.env.GHL_API_KEY}`, Version: '2021-07-28' } }
    )
    const data = await res.json()
    const c = data.contacts?.[0]
    if (!c) return null
    return { id: c.id, name: `${c.firstName || ''} ${c.lastName || ''}`.trim() }
  } catch { return null }
}

async function addGhlNote(contactId: string, note: string): Promise<void> {
  if (!process.env.GHL_API_KEY) return
  await fetch(`https://services.leadconnectorhq.com/contacts/${contactId}/notes/`, {
    method: 'POST',
    headers: { Authorization: `Bearer ${process.env.GHL_API_KEY}`, Version: '2021-07-28', 'Content-Type': 'application/json' },
    body: JSON.stringify({ body: note }),
  })
}

export async function GET(req: NextRequest) {
  if (!isAuthorized(req)) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  if (!process.env.GOOGLE_REFRESH_TOKEN) return NextResponse.json({ ok: false, message: 'Google not connected' })

  const auth = await getAuthedClient()
  const drive = google.drive({ version: 'v3', auth })
  const gmail = google.gmail({ version: 'v1', auth })

  // Search for Meet transcript docs created in the last 35 minutes
  const since = new Date(Date.now() - 35 * 60 * 1000).toISOString()
  const query = `mimeType='application/vnd.google-apps.document' and (name contains 'transcript' or name contains 'Transcript') and createdTime > '${since}'`

  const { data } = await drive.files.list({
    q: query,
    fields: 'files(id, name, createdTime, owners)',
    orderBy: 'createdTime desc',
    pageSize: 10,
  })

  const files = data.files || []
  if (!files.length) return NextResponse.json({ ok: true, message: 'No new Meet transcripts found' })

  const logs: string[] = []
  const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY! })

  for (const file of files) {
    try {
      // Export Google Doc as plain text
      const exportRes = await drive.files.export({ fileId: file.id!, mimeType: 'text/plain' }, { responseType: 'text' })
      const rawText = (exportRes.data as string).slice(0, 8000)

      // Extract meeting title from filename — "Meeting transcript - Title - Date"
      const titleMatch = file.name?.match(/transcript[- ]+(.+?)(?:\s*[-–]\s*\d{4}|$)/i)
      const meetingTitle = titleMatch?.[1]?.trim() || file.name || 'Google Meet'

      const createdAt = new Date(file.createdTime || Date.now()).toLocaleString('en-GB', {
        timeZone: TZ, weekday: 'long', day: 'numeric', month: 'long', year: 'numeric', hour: '2-digit', minute: '2-digit', hour12: false,
      })

      // Generate summary
      const aiRes = await anthropic.messages.create({
        model: 'claude-sonnet-4-6',
        max_tokens: 1500,
        messages: [{
          role: 'user',
          content: `You are the executive assistant to Dr. Siamak Goudarzi, Founder of Nexter AI Group.

A Google Meet just ended. Generate a structured meeting report.

MEETING: ${meetingTitle}
DATE: ${createdAt}
SOURCE: Google Meet (auto-transcript)

TRANSCRIPT:
${rawText}

Write a meeting report with these sections:
1. SUMMARY (2–3 sentences: what was discussed, what was decided)
2. KEY POINTS (bullet list)
3. ACTION ITEMS (what needs to happen next, who is responsible)
4. CLIENT SENTIMENT (positive / neutral / needs attention)
5. FOLLOW-UP RECOMMENDED (specific next step with timeline)

Be precise and professional. Plain text only.`,
        }],
      })

      const summary = (aiRes.content[0] as { type: 'text'; text: string }).text
      const datePrefix = new Date().toISOString().slice(0, 10)
      const safeName = meetingTitle.replace(/[^a-zA-Z0-9\s-]/g, '').replace(/\s+/g, '-').slice(0, 50)
      const filename = `${datePrefix}-meet-${safeName}.md`

      // Save to meetings/ folder
      const dir = path.join(process.cwd(), 'meetings')
      await fs.mkdir(dir, { recursive: true })
      await fs.writeFile(path.join(dir, filename), `# ${meetingTitle}\nDate: ${createdAt}\nSource: Google Meet\n\n${summary}\n\n---\n*Auto-generated by Nexter AI VA*\n`, 'utf-8')

      // Find contact in GHL by meeting title keywords
      const searchTerm = meetingTitle.split(/\s+/).slice(0, 3).join(' ')
      const contact = await findGhlContact(searchTerm)
      if (contact) {
        await addGhlNote(contact.id, `GOOGLE MEET SUMMARY — ${createdAt}\nMeeting: ${meetingTitle}\n\n${summary}`)
      }

      // Send summary email
      const to = process.env.BRIEFING_EMAIL || process.env.GOOGLE_ACCOUNT_EMAIL || 'info@i-review.ai'
      const subject = `Meet Summary: ${meetingTitle} — ${datePrefix}`
      const emailBody = `GOOGLE MEET SUMMARY\n${'─'.repeat(50)}\nMeeting: ${meetingTitle}\nDate: ${createdAt}\n\n${summary}\n\n${'─'.repeat(50)}\nSaved to: meetings/${filename}${contact ? `\nLogged in CRM for: ${contact.name}` : ''}`
      const raw = Buffer.from(
        [`To: ${to}`, `Subject: ${subject}`, 'MIME-Version: 1.0', 'Content-Type: text/plain; charset=utf-8', '', emailBody].join('\r\n')
      ).toString('base64url')
      await gmail.users.messages.send({ userId: 'me', requestBody: { raw } })

      logs.push(`Processed: ${meetingTitle} → ${filename}`)
    } catch (err) {
      logs.push(`Error processing ${file.name}: ${String(err)}`)
    }
  }

  return NextResponse.json({ ok: true, processed: logs.length, logs })
}
