import { NextRequest, NextResponse } from 'next/server'
import { google } from 'googleapis'
import { getAuthedClient } from '@/lib/google'
import {
  generateMeetingSummary,
  saveMeetingToDrive,
  saveMeetingLocally,
  findGhlContact,
  addGhlNote,
  sendMeetingEmail,
  sendNoTranscriptAlert,
  buildMeetingEmailHtml,
} from '@/lib/meeting-report'

function isAuthorized(req: NextRequest) {
  return req.headers.get('authorization') === `Bearer ${process.env.CRON_SECRET}`
}

const TZ = 'Europe/Budapest'

// Search window: 2.5 hours — matches the every-2-hour cron with 30-min overlap
const WINDOW_MS = 2.5 * 60 * 60 * 1000

export async function GET(req: NextRequest) {
  if (!isAuthorized(req)) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  if (!process.env.GOOGLE_REFRESH_TOKEN) return NextResponse.json({ ok: false, message: 'Google not connected' })

  const auth = await getAuthedClient()
  const drive = google.drive({ version: 'v3', auth })

  // Find Meet transcript docs created in the search window
  const since = new Date(Date.now() - WINDOW_MS).toISOString()
  const query = [
    `mimeType='application/vnd.google-apps.document'`,
    `(name contains 'transcript' or name contains 'Transcript' or name contains 'Meet transcript')`,
    `createdTime > '${since}'`,
    `trashed=false`,
  ].join(' and ')

  const { data } = await drive.files.list({
    q: query,
    fields: 'files(id, name, createdTime)',
    orderBy: 'createdTime desc',
    pageSize: 20,
  })

  const files = data.files || []

  // No transcripts found — send alert asking for manual notes
  if (!files.length) {
    // Check if there were any Google Meet calendar events in the window
    const calendarAuth = await getAuthedClient()
    const calendar = google.calendar({ version: 'v3', auth: calendarAuth })
    const calRes = await calendar.events.list({
      calendarId: 'primary',
      timeMin: new Date(Date.now() - WINDOW_MS).toISOString(),
      timeMax: new Date().toISOString(),
      singleEvents: true,
      q: 'meet.google.com',
    })

    const meetEvents = (calRes.data.items || []).filter(e =>
      e.hangoutLink || e.conferenceData?.entryPoints?.some(ep => ep.uri?.includes('meet.google.com'))
    )

    if (meetEvents.length) {
      // There was a Google Meet but no transcript — send alert
      for (const event of meetEvents) {
        const title = event.summary || 'Google Meet'
        const startDate = new Date(event.start?.dateTime || event.start?.date || Date.now())
          .toLocaleString('en-GB', { timeZone: TZ, weekday: 'long', day: 'numeric', month: 'long', year: 'numeric', hour: '2-digit', minute: '2-digit', hour12: false })
        await sendNoTranscriptAlert(
          title,
          startDate,
          `${process.env.NEXT_PUBLIC_APP_URL || 'https://va.nexterai.agency'}/api/meetings/notes`
        ).catch(console.error)
      }
      return NextResponse.json({ ok: true, message: `No transcripts found — sent ${meetEvents.length} alert(s) for detected Meet events` })
    }

    return NextResponse.json({ ok: true, message: 'No new Meet transcripts and no recent Meet events found' })
  }

  const logs: string[] = []

  for (const file of files) {
    try {
      // Export Google Doc as plain text
      const exportRes = await drive.files.export(
        { fileId: file.id!, mimeType: 'text/plain' },
        { responseType: 'text' }
      )
      const rawText = (exportRes.data as string).slice(0, 8000)

      // Parse meeting title from filename: "Meet transcript - Title - Date" or "Transcript of Title"
      const titleMatch =
        file.name?.match(/(?:transcript(?:\s+of)?)[- ]+(.+?)(?:\s*[-–]\s*\d{4}|$)/i) ||
        file.name?.match(/^(.+?)\s*[-–]\s*transcript/i)
      const meetingTitle = titleMatch?.[1]?.trim() || file.name || 'Google Meet'

      const createdAt = new Date(file.createdTime || Date.now()).toLocaleString('en-GB', {
        timeZone: TZ, weekday: 'long', day: 'numeric', month: 'long', year: 'numeric', hour: '2-digit', minute: '2-digit', hour12: false,
      })
      const datePrefix = new Date(file.createdTime || Date.now()).toISOString().slice(0, 10)

      // Generate summary
      const summary = await generateMeetingSummary(meetingTitle, createdAt, rawText)

      const fileContent = `# ${meetingTitle}\nDate: ${createdAt}\nSource: Google Meet\n\n${summary}\n\n---\n*Auto-generated by Nexter AI VA*\n`

      // Save locally (backup) + to Google Drive
      const safeName = meetingTitle.replace(/[^a-zA-Z0-9\s-]/g, '').replace(/\s+/g, '-').slice(0, 50)
      const localFilename = `${datePrefix}-meet-${safeName}.md`
      await saveMeetingLocally(localFilename, fileContent)
      const driveUrl = await saveMeetingToDrive(meetingTitle, fileContent, datePrefix)

      // Find contact in GHL
      const searchTerm = meetingTitle.split(/\s+/).slice(0, 3).join(' ')
      const contact = await findGhlContact(searchTerm)
      if (contact) {
        await addGhlNote(contact.id, `GOOGLE MEET SUMMARY — ${createdAt}\nMeeting: ${meetingTitle}\n\n${summary}`)
      }

      // Send styled email
      const html = buildMeetingEmailHtml({
        title: meetingTitle,
        date: createdAt,
        source: 'Google Meet',
        summary,
        driveUrl,
        contactName: contact?.name || null,
      })
      await sendMeetingEmail(`📋 Meet Summary: ${meetingTitle} — ${datePrefix}`, html)

      logs.push(`✓ ${meetingTitle} → Drive: ${driveUrl ? 'saved' : 'failed'} | CRM: ${contact ? contact.name : 'not found'}`)
    } catch (err) {
      logs.push(`✗ Error processing ${file.name}: ${String(err)}`)
      console.error('[meet-transcripts] Error:', err)
    }
  }

  return NextResponse.json({ ok: true, processed: logs.length, logs })
}
