import { NextRequest, NextResponse } from 'next/server'
import crypto from 'crypto'
import {
  generateMeetingSummary,
  saveMeetingToDrive,
  saveMeetingLocally,
  findGhlContact,
  addGhlNote,
  sendMeetingEmail,
  buildMeetingEmailHtml,
} from '@/lib/meeting-report'

// ── Webhook verification ──────────────────────────────────────────────────────

function verifyZoomWebhook(req: NextRequest, body: string): boolean {
  const secret = process.env.ZOOM_WEBHOOK_SECRET
  if (!secret) return true
  const timestamp = req.headers.get('x-zm-request-timestamp') || ''
  const signature = req.headers.get('x-zm-signature') || ''
  const message = `v0:${timestamp}:${body}`
  const hash = 'v0=' + crypto.createHmac('sha256', secret).update(message).digest('hex')
  return hash === signature
}

// ── Download Zoom transcript (VTT) ───────────────────────────────────────────

async function downloadTranscript(downloadUrl: string, downloadToken: string): Promise<string> {
  const res = await fetch(`${downloadUrl}?access_token=${downloadToken}`)
  if (!res.ok) throw new Error(`Transcript download failed: ${res.status}`)
  const vtt = await res.text()
  return vtt
    .split('\n')
    .filter(line =>
      line &&
      !line.startsWith('WEBVTT') &&
      !line.match(/^\d+$/) &&
      !line.match(/^\d{2}:\d{2}/) &&
      !line.startsWith('NOTE')
    )
    .join(' ')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, 8000)
}

// ── Main webhook handler ──────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  const rawBody = await req.text()

  let payload: Record<string, unknown>
  try { payload = JSON.parse(rawBody) } catch {
    return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 })
  }

  // Zoom URL validation challenge
  if (payload.event === 'endpoint.url_validation') {
    const plainToken = (payload.payload as Record<string, string>)?.plainToken || ''
    const secret = process.env.ZOOM_WEBHOOK_SECRET || ''
    const encryptedToken = crypto.createHmac('sha256', secret).update(plainToken).digest('hex')
    return NextResponse.json({ plainToken, encryptedToken })
  }

  if (!verifyZoomWebhook(req, rawBody)) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const handled = ['recording.completed', 'recording.transcript_completed']
  if (!handled.includes(payload.event as string)) {
    return NextResponse.json({ ok: true, skipped: true })
  }

  // Respond immediately — Zoom retries if we don't respond fast
  processRecording(payload).catch(err => console.error('[Zoom webhook]', err))
  return NextResponse.json({ ok: true })
}

async function processRecording(payload: Record<string, unknown>) {
  const downloadToken = payload.download_token as string
  const obj = payload.payload as Record<string, unknown>
  const meeting = obj?.object as Record<string, unknown>

  const topic = (meeting?.topic as string) || 'Meeting'
  const hostEmail = (meeting?.host_email as string) || ''
  const startDate = new Date((meeting?.start_time as string) || Date.now())
  const datePrefix = startDate.toISOString().slice(0, 10)
  const startTime = startDate.toLocaleString('en-GB', {
    timeZone: 'Europe/Budapest', weekday: 'long', day: 'numeric', month: 'long', year: 'numeric', hour: '2-digit', minute: '2-digit', hour12: false,
  })
  const duration = (meeting?.duration as number) || 0
  const recordingFiles = (meeting?.recording_files as Record<string, unknown>[]) || []

  // Download transcript if available
  const transcriptFile = recordingFiles.find(f =>
    (f.file_type as string) === 'TRANSCRIPT' || (f.recording_type as string) === 'audio_transcript'
  )
  let transcript = ''
  if (transcriptFile && downloadToken) {
    try {
      transcript = await downloadTranscript(transcriptFile.download_url as string, downloadToken)
    } catch (err) {
      console.error('[Zoom] Transcript download error:', err)
    }
  }

  // Generate summary
  const summary = await generateMeetingSummary(topic, startTime, transcript, duration)

  const safeTopic = topic.replace(/[^a-zA-Z0-9\s-]/g, '').replace(/\s+/g, '-').slice(0, 50)
  const localFilename = `${datePrefix}-zoom-${safeTopic}.md`
  const fileContent = `# ${topic}\nDate: ${startTime}\nDuration: ${duration} min\nHost: ${hostEmail}\nSource: Zoom\n\n${summary}\n\n---\n*Auto-generated by Nexter AI VA*\n`

  // Save locally + to Google Drive
  await saveMeetingLocally(localFilename, fileContent)
  const driveUrl = await saveMeetingToDrive(topic, fileContent, datePrefix)

  // Log to GHL CRM (search by host email first, then topic)
  let contact = await findGhlContact(hostEmail)
  if (!contact) contact = await findGhlContact(topic.split(/\s+/).slice(0, 3).join(' '))
  if (contact) {
    await addGhlNote(contact.id, `ZOOM MEETING SUMMARY — ${startTime}\nTopic: ${topic}\nDuration: ${duration} min\n\n${summary}`)
  }

  // Send styled email
  const html = buildMeetingEmailHtml({
    title: topic,
    date: startTime,
    source: 'Zoom',
    summary,
    driveUrl,
    contactName: contact?.name || null,
    durationMin: duration,
  })
  await sendMeetingEmail(`📋 Zoom Summary: ${topic} — ${datePrefix}`, html)

  console.log(`[Zoom] Processed: ${topic} → Drive: ${driveUrl ? 'saved' : 'failed'} | CRM: ${contact ? contact.name : 'not found'}`)
}
